### ISSUE TITLE
curl is not installed in jnlp agent based image

### ISSUE THREAD

**Issue by vutkin** [jenkinsci/docker-agent#153]
Hi all,

could you please explain why did you delete curl from based image:

https://github.com/jenkinsci/docker-agent/blob/master/8/alpine/Dockerfile#L45

It's better to have git/curl in jnlp images.

**Comment by MarkEWaite** [comment]
> could you please explain why did you delete curl from based image:

The line was added 4 years ago by @carlossg when alpine agents were enabled.  I believe the general pattern is to avoid including only the required components in an agent image.  Fewer components means fewer chances for issues with components.

Command line git is bundled with the agent images because it is the preferred SCM system for the majority of Jenkins users.

**Comment by nikoooo20** [comment]
I hope you reconsider to install curl back to the image. Our Jenkins library uses curl a lot to integrate job states to the git. 

If curl installation is not possible, then I ask you to provide workaround to install it.

**Comment by bjrke** [comment]
In the jenkins documentation it is suggested to use `curl`, `wget` or `jq` instead of complex groovy code:
https://www.jenkins.io/doc/book/pipeline/pipeline-best-practices/#avoiding-complex-groovy-code-in-pipelines

I would say extending a docker container is much more complex (because of maintenance overhead) then writing some complex groovy code.

**Comment by danielwegener** [comment]
This essentially breaks custom tool installation/download for us for tools that are NOT hosted as archive but static binaries (like many releases on github).

**Comment by sameer1046** [comment]
Pls add necessary command line tool curl

**Comment by MarkEWaite** [comment]
> Any news on this ?

We don't plan to add curl to the agent image.  If you need curl installed on your agent image, you should create a custom agent image with the tools that you need (including curl).  See my comment at https://github.com/jenkinsci/docker-agent/issues/153#issuecomment-1052981392 and see the link from @timja at https://github.com/jenkinsci/docker-agent/issues/253#issuecomment-1123296544

**Comment by gounthar** [comment]
If you need help creating and hosting your docker agent-based image containing curl, we could try to pair one of these days.
I'm not skilled, but I've done it several times.

**Comment by dduportal** [comment]
Reopening as discussed by maintainers in IRC: the value of adding `curl` is still high given the (small) overhead it had.

Besides, `curl` is used in the image during the build process to retrieve the remoting JAR file and is then deleted.

Please note that `wget` won't be an option as `curl` has the same feature set.

**Comment by dduportal** [comment]
https://github.com/jenkinsci/docker-agent/pull/321

**Comment by sameer1046** [comment]
Great

**Comment by dduportal** [comment]
(Wait for the release to be availble: I'll comment here)

**Comment by n00bdevel0per** [comment]
Will this work on fargate?
