### ISSUE TITLE
how can I use 'docker' commad with this image？

### ISSUE THREAD

**Issue by spjich** [jenkinsci/docker-agent#76]
I run  this image by using following command 
`docker run -itd  --name agent --init  --privileged -v /usr/local/bin/docker:/usr/bin/docker   -v /var/run/docker.sock:/var/run/docker.sock   jenkins/slave`

but, i got 'permission denied' when i building  pipeline because of my jenkinsFiles use `agent docker ` and `docker.sock` mounted on this container has no right  permission. 

how can I use it?

**Comment by avillev** [comment]
I am trying to achieve the same thing. I even added the Jenkins user into the "docker" group in my DockerFile but when my job starts. I end up not seeing my new group for some reasons.

My docker file:
```java
FROM jenkins/agent:latest-jdk11
USER root
RUN apt-get update
RUN apt-get install docker.io -y
RUN usermod -a -G docker jenkins
RUN su -c "id" jenkins
```

My pipeline's agent definition:

```java
agent {
        dockerfile {
            filename 'Dockerfile'
            additionalBuildArgs ''
            args '-v $HOME/.m2:/home/jenkins/.m2 -v /tmp:/tmp -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
```

Could anyone advise us ?

**Comment by GunArm** [comment]
I have had this working for a while.  

If all you do is set up the volume, it will be owned by group "docker" and the "jenkins" user (from the ssh-agent base image) will not be able to access it.

You could add the "jenkins" user to the "docker" group with `RUN usermod -aG docker jenkins`, but that only works if the "docker" group on the host has the same **numerical ID** as the "docker" group in the container.  If they don't match, the container will just see the numerical ID of the hosts "docker" group when doing an "ls -la", and permission will be denied.

What I finally did to get around this was `chmod 666 /var/run/docker.sock` on the host.  Note that there may be security concerns about this you should consider.

Also, while the above shows the concept, it's not practical on it's own because each time the docker service is (re)started, the sock file will be recreated, and permissions you set on it will be reverted.  In order to institute this permanently, you need to somehow reset that permission each time dockerd is started.  

In ubuntu, I ran `sudo servicectl edit docker.service` and add a line `ExecStartPost=chmod 666 /var/run/docker.sock`  Now when you run `sudo servicectl restart docker`, the permissions on /var/run/docker.sock should show srw-rw-rw-.

Hopefully this helps
